### ISSUE TITLE
数据库连接的问题

### ISSUE THREAD

**Issue by MZMZj19960615** [hunter-lee1/guanchazhe_spider#1]
你好，请问有没有mysql数据库的文件？

**Comment by hunter-lee1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hunter-lee1/guanchazhe_spider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月20日(星期三) 下午4:34
收件人:&nbsp;"hunter-lee1/guanchazhe_spider"<guanchazhe_spider@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hunter-lee1/guanchazhe_spider] 数据库连接的问题 (#1)





 
你好，请问有没有mysql数据库的文件？

**Comment by EITSxiaozhai** [comment]
同求，数据库呢

**Comment by hunter-lee1** [comment]
数据库只需要在自己的数据库里按照程序段要求的格式自己建一张表就可以了（只需要建立一张表 对各位来说应该不会是太大的问题吧？

**Comment by hunter-lee1** [comment]
![image](https://user-images.githubusercontent.com/35529532/139216518-cb04fff0-55a4-4835-abec-1608a28ef6b9.png)


尝试使用一下这张表？ 很久以前写的代码了（没想到还有人在关注 等最近有时间了 我再更新一版吧！

**Comment by hunter-lee1** [comment]
[guanchazhe.txt](https://github.com/hunter-lee1/guanchazhe_spider/files/7432501/guanchazhe.txt)
这个是导出的sql文件（转成了txt），但是我没测试过是否可以使用。
不过项目所需求的表就一张，可以手工按照上述参数自己设定一下。
如果可以自动化完成，帮到大家也最好了。
（我实在是太懒了QAQ

**Comment by hajiuke** [comment]
楼主  您好 能有偿请你帮忙改下东西嘛

**Comment by Viperkn** [comment]
楼主，我运行后新闻总数为0，没爬到新闻

**Comment by qq14770** [comment]
spider_modul这个不生效该怎么弄
